chore: tm retry container start (#296)
As we still get conflicts on ports somehow 🤷, we introduce retries to
start the container.

```
test_manager.go:143: 
[539](https://github.com/babylonlabs-io/vigilante/actions/runs/14154681891/job/39652388908?pr=295#step:7:540)
        	Error Trace:	/home/runner/work/vigilante/vigilante/e2etest/test_manager.go:143
[540](https://github.com/babylonlabs-io/vigilante/actions/runs/14154681891/job/39652388908?pr=295#step:7:541)
        	            				/home/runner/work/vigilante/vigilante/e2etest/reporter_e2e_test.go:259
[541](https://github.com/babylonlabs-io/vigilante/actions/runs/14154681891/job/39652388908?pr=295#step:7:542)
        	Error:      	Received unexpected error:
[542](https://github.com/babylonlabs-io/vigilante/actions/runs/14154681891/job/39652388908?pr=295#step:7:543)
        	            	API error (500): driver failed programming external connectivity on endpoint babylond-TestReporter_Censorship (4d382b3ffa9e56e14402a5808249287453f1f08b8a2b8055d6fec51811042b84): Error starting userland proxy: listen tcp4 0.0.0.0:37766: bind: address already in use
```